export { default as Home } from './Home.vue';
export { default as Hosts } from './Hosts.vue';
export { default as Clusters } from './Clusters.vue';
export { default as Tasks } from './Tasks.vue';
export { default as TaskRuns } from './TaskRuns.vue';
export { default as Pipelines } from './Pipelines.vue';
export { default as PipelineRuns } from './PipelineRuns.vue';
export { default as Login } from './Login.vue';
export { default as Copilot } from './Copilot.vue'