FROM golang:1.19 as builder
WORKDIR /workspace
COPY . .
RUN go build  -o bin/opsserver cmd/server/main.go

FROM ubuntu:latest
WORKDIR /
COPY --from=builder /workspace/bin/opsserver .
ENTRYPOINT ["/opsserver"]
Expose 8080