FROM hubimage/builder-golang:1.19 as builder
COPY . .
RUN go build -o bin/ops-server cmd/server/main.go

FROM hubimage/runtime-ubuntu:22.04
COPY --from=builder /builder/bin/ops-server .
COPY --from=builder /builder/default.toml .
ENTRYPOINT ["./ops-server", "-c", "./default.toml"]
Expose 80
